[package]
name = "gfaR"
version = "0.1.3"
authors = ["moinSebi <s.vorbrugg@googlemail.com>"]

edition = "2018"
license = "MIT"
description = "Reading gfa format v1"
repository = "https://github.com/MoinSebi/gfaR"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
